repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
        language_version: python3.11

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - Flake8-pyproject
          - flake8-blind-except
          - flake8-print
          - flake8-breakpoint
          - flake8-expression-complexity
          - flake8-mutable
          - flake8-return
          - pep8-naming
          - flake8-docstrings
          - flake8-pytest
          - flake8-todo
          # - flake8-broken-line
          - flake8-comprehensions
          - flake8-builtins
          # - flake8-eradicate
          - flake8-quotes

  - repo: local
    hooks:
      - id: poetry-mypy
        name: poetry-mypy
        entry: poetry run mypy
        require_serial: true
        language: system
        types: [ python ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.7'
    hooks:
      - id: vulture

  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
      # - id: poetry-lock

default_language_version:
  python: python3.11
